### ISSUE TITLE
Bad reference to the "Zacas" extension

### ISSUE THREAD

**Issue by anderslindgren-iar** [riscv/riscv-zaamo-zalrsc#10]
On page 2, there is a short paragraph on the form:

> The Zacas extension depends on the Zaamo extension.

However, there is no explanation what "Zacas" is and there are no other references to the "Zacas" extension.

Unfortunately, I don't know the exact status of the "Zacas" extension, so there might be multiple ways to deal with this:

* If "Zacas" is a ratified extension, this document should contain a reference to where it is defined, what version it refers to etc.

* If "Zacas" is *not* a ratified extension, this sentence should be removed. (Should "Zacas" be ratified in the future, the documentation for that extension should specify exactly which extensions that it depends on.)

**Comment by ved-rivos** [comment]
Zacas is a ratified extension that provides the compare-and-swap instructions - the specifications for all ratified extensions are located [here](https://wiki.riscv.org/display/HOME/Recently+Ratified+Extensions). Will add a bibliography section to provide links to the Priv and Zacas standard extensions.

**Comment by ved-rivos** [comment]
PR #12 created to include references to Unpriv and Zacas extensions.
