### ISSUE TITLE
Splitting extensions makes it harder to provide libraries, please reduce legal combinations

### ISSUE THREAD

**Issue by anderslindgren-iar** [riscv/riscv-zaamo-zalrsc#11]
**Note**: This is not the first time I have brought up this topic -- and it will probably not be the last...

Splitting standard extensions into smaller parts may look like a good idea -- at least from the perspective of hardware implementation.

Unfortunately, when it comes to providing tools and libraries this has the opposite effect. To provide a RISC-V library today it must be built in multiple ways. For example -- for RV32E, RV32I, and RV64 -- for five different floating-point variants (none, F, D, ZFinx, ZDinx) -- for C and non-C -- and (until now) for devices with or without A.

By splitting A into two groups you have doubled the number of libraries that must be built:

* No atomic support
* Zaamo
* Zalrsc
* Zaamo + Zalrsc (a.k.a. A)

Before you go ahead -- please give it a though if all four combinations are sane. For example, will there ever be hardware that provide Zalrsc but not Zaamo? If the answer to that question is "no" then update the documentation so that "Zalrsc" requires "Zaamo".

**Comment by ved-rivos** [comment]
The fetch-and-op style atomic primitives provided by the A extension support better scaling for highly parallel systems. Implementations that do not have such scaling requirements or can achieve this through other techniques like monitors in the fabric may implement the just the Zalrsc subset of the A extension to support atomic primitives. 

There are implementations which have supported LR/SC but not AMO* - please see an example Section VII of this [paper](https://fpga.org/wp-content/uploads/2016/05/grvi_phalanx_fccm2016.pdf) and this discussion on [hw-dev](https://groups.google.com/a/groups.riscv.org/g/hw-dev/c/Mt9Q94f_l2w/m/vL0lWMPoGQAJ).

Standard toolchains may end up only supporting the profiles mandated combinations or combination of extensions that are compatible with the ABI. A number of such subset implementation however may not have a need to comply with an ABI. These extensions provide the maximal flexibility to optimize the implementation for the specific target applications.

**Comment by ved-rivos** [comment]
Hope that addressed the question.
