### ISSUE TITLE
Does Zacas depend on A or Zaamo

### ISSUE THREAD

**Issue by topperc** [riscv/riscv-zaamo-zalrsc#5]
The Zacas spec says it depends on A. Now that A is being split, does Zacas still depend on all of A or just Zaamo?

**Comment by ved-rivos** [comment]
With Zacas being ratified as depending on A, the strictest interpretation would be that it depends on A and not just Zaamo. Is there a case to allow Zacas with the Zaamo subset?

**Comment by ved-rivos** [comment]
So while the strictest interpretation is it depends on all of A, the right interpretation is that it depends on Zaamo.
I am adding this to the Zaamo extension - The Zacas extension depends on the Zaamo extension - please see PR #6 
@topperc @dtcxzyw

**Comment by ved-rivos** [comment]
Hope that clarifies.
