### ISSUE TITLE
Test case for idiosyncrasy when [rd] is x0

### ISSUE THREAD

**Issue by psherman42** [riscv/riscv-zaamo-zalrsc#8]
Can we consider including a test case to characterize the idiosyncratic behavior of an implementation when an amoxxx.w instruction's destination register _rd_ is the _zero_ register, x0?
In case of real-world example of FE310, this idiosyncratic nature has to do with pipeline hazards, and the lack thereof, when writing to the "dummy" register. See detailed explanation at [Demonstrating AMO](https://github.com/psherman42/Demonstrating-AMO)

**Comment by ved-rivos** [comment]
@psherman42 thanks for the link to these tests. Generally ISA specifications do not delve on the implementation microarchitectures. This specification is not a good home for such references. I would suggest you provide this on isa-dev and on unpriv mail lists to educate a wider audience about your findings.

**Comment by ved-rivos** [comment]
Closing this issue.
